name: Daniel W. Halseth
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Thoughts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b9996a'
    - '#926836'
    - '#d7c09e'
    - '#1f0b02'
    - '#633712'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
