name: Daniel Halseth
favicon: null
layout_spectrum: 0.75963
typography_spectrum: 0.60854
title: Daniel Halseth Thoughts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2d2219'
    - '#e6f5f5'
    - '#efccb4'
    - '#4f5619'
    - '#a68822'
  brandStrength: 0.5
  lightness: 0.7550017409957945
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
