name: Daniel W. Halseth
favicon: null
layout_spectrum: 0.84429
typography_spectrum: 0.9413
title: Daniel Halseth
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3e3f41'
    - '#18080b'
    - '#efefef'
    - '#a4a5a0'
    - '#a2314a'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
