name: Daniel W. Halseth
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Daniel Halseth
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c09f72'
    - '#ddc8a7'
    - '#f4ecdf'
    - '#1e0700'
    - '#50270b'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
